spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/JavaEE-combat
    username: root
    password: root
  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1GB
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
SECRET: ZZZCNY
